spring:
  application:
    name: strategy
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update